config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#search'
  resources :items, only: %i[search create destroy]
  resources :users, only: %i[show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def search
    if params[:keyword]
      @items = RakutenWebService::Ichiba::Product.search(keyword: params[:keyword])
    end
  end

  def create
    current_user.items.create!(name: params[:name], genre: params[:genre], image: params[:image])
    redirect_to user_path(current_user)
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy!
    redirect_to user_path(current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_item.html.erb
<table>
  <thead>
    <tr>
      <th>画像</th>
      <th>商品名</th>
      <th>ジャンル</th>
      <th>アイテムを追加</th>
    </tr>
  </thead>
  <tbody>
    <% if @items.present? %>
      <% @items.each do |item| %>
        <tr>
          <td><%= image_tag item['mediumImageUrl'] %></td>
          <td><%= link_to item['productName'], "#{item['affiliateUrl']}" %></td>
          <td><%= item['genreName'] %></td>
          <td><%= link_to "＋", items_path(name: item['productName'], genre: item['genreName'], image: item['mediumImageUrl']), method: :post %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/items/search.html.erb
<h1>商品検索</h1>
<%= form_with url: root_path, method: :get, local: true do |form| %>
  <%= form.text_field :keyword %>
  <%= form.submit "検索" %>
<% end %>
<% if @items.present? %>
  <%= render partial: "item" %>
<% end %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <%= link_to "商品検索", root_path %>
  <%= link_to "アカウント編集", edit_user_registration_path %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
  <%= link_to user_path(current_user) do %>
    <%= "【ログイン中のユーザー】#{current_user.email}" %>
  <% end %>
<% else %>
  <%= link_to "新規登録", new_user_registration_path %>
  <%= link_to "ログイン", new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RakutenApiPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>マイページ</h1>
<p>メールアドレス : <%= @user.email %></p>
<table>
  <thead>
    <tr>
      <th>画像</th>
      <th>商品名</th>
      <th>ジャンル</th>
      <th>削除</th>
    </tr>
  </thead>
  <tbody>
    <% if @user.items.present? %>
      <% @user.items.each do |item| %>
        <tr>
          <td><%= image_tag item.image %></td>
          <td><%= item.name %></td>
          <td><%= item.genre %></td>
          <td><%= link_to "x", item_path(item), method: :delete, data: {confirm: "削除しますか？"} %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>